export const VehicleList = [
  {
    type: "car",
    name: "Volvo",
    doors: 4,
    wheels: 4,
    color: "blue",
    draghook: false,
    year: 2021,
  },
  {
    type: "boat",
    name: "Buster",
    color: "white",
    outsidemotor: true,
  },
  {
    type: "motorcycle",
    name: "Yamaha",
    wheels: 2,
    year: 2020,
    color: "red",
  },
  {
    type: "car",
    name: "Audi",
    doors: 4,
    wheels: 4,
    color: "black",
    draghook: true,
    year: 2019,
  },
  {
    type: "boat",
    name: "Yamarin",
    color: "blue",
    outsidemotor: false,
  },
  {
    type: "motorcycle",
    name: "Kawasaki",
    wheels: 2,
    year: 2018,
    color: "green",
  },
  {
    type: "car",
    name: "BMW",
    doors: 2,
    wheels: 4,
    color: "yellow",
    draghook: false,
    year: 2017,
  },
  {
    type: "boat",
    name: "Silver",
    color: "black",
    outsidemotor: true,
  },
  {
    type: "motorcycle",
    name: "Suzuki",
    wheels: 2,
    year: 2016,
    color: "white",
  },
  {
    type: "car",
    name: "Ford",
    doors: 4,
    wheels: 4,
    color: "red",
    draghook: true,
    year: 2015,
  },
  {
    type: "boat",
    name: "Bella",
    color: "green",
    outsidemotor: false,
  },
  {
    type: "motorcycle",
    name: "Harley-Davidson",
    wheels: 2,
    year: 2014,
    color: "blue",
  },
  {
    type: "car",
    name: "Toyota",
    doors: 4,
    wheels: 4,
    color: "white",
    draghook: false,
    year: 2013,
  },
  {
    type: "boat",
    name: "Quicksilver",
    color: "red",
    outsidemotor: true,
  },
  {
    type: "motorcycle",
    name: "Honda",
    wheels: 2,
    year: 2012,
    color: "black",
  },
  {
    type: "car",
    name: "Mercedes",
    doors: 2,
    wheels: 4,
    color: "blue",
  },
  {
    type: "boat",
    name: "Terhi",
    color: "yellow",
    outsidemotor: false,
  },
  {
    type: "motorcycle",
    name: "Ducati",
    wheels: 2,
    year: 2011,
    color: "green",
  },
];

export default VehicleList;
